# Generated by Django 5.2.4 on 2025-07-14 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_post_category_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 16, 3, 59, 458996, tzinfo=datetime.timezone.utc)),
        ),
    ]
