# Generated by Django 5.2.3 on 2025-07-16 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 9, 23, 5, 175460, tzinfo=datetime.timezone.utc)),
        ),
    ]
