# Generated by Django 5.2.3 on 2025-07-16 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 14, 50, 19, 995428, tzinfo=datetime.timezone.utc)),
        ),
    ]
